// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc7ZZvJq-jz39VVNIvYMC2zs1RIgof5dE',
    appId: '1:1081190770163:web:7dc679ba2f77ba5c401e86',
    messagingSenderId: '1081190770163',
    projectId: 'shopeweb-24620',
    authDomain: 'shopeweb-24620.firebaseapp.com',
    storageBucket: 'shopeweb-24620.appspot.com',
    measurementId: 'G-2PEDX2Z4BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbi9OYNdxLlshEsCRfS3icw-wYOy-Q4lQ',
    appId: '1:1081190770163:android:33a6c754bd2f21e2401e86',
    messagingSenderId: '1081190770163',
    projectId: 'shopeweb-24620',
    storageBucket: 'shopeweb-24620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsuF53vkkPo4aPoSKgCUASrGqD9v79Shs',
    appId: '1:1081190770163:ios:c6b99d9de2f84207401e86',
    messagingSenderId: '1081190770163',
    projectId: 'shopeweb-24620',
    storageBucket: 'shopeweb-24620.appspot.com',
    iosBundleId: 'com.example.shopeWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsuF53vkkPo4aPoSKgCUASrGqD9v79Shs',
    appId: '1:1081190770163:ios:403e0c604aa9b44b401e86',
    messagingSenderId: '1081190770163',
    projectId: 'shopeweb-24620',
    storageBucket: 'shopeweb-24620.appspot.com',
    iosBundleId: 'com.example.shopeWeb.RunnerTests',
  );
}
